trigger:
  batch: true
  branches:
    include:
      - master
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - master
      - stable-*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: python3 -m pip install pytest pytest-cov
    displayName: Install deps

  - script: pytest
    displayName: Run tests

  - script: ./publish-codecov.sh
    displayName: Upload coverage report
